name: crepito99
description: A food order delivery restaurant app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  url_launcher: ^5.0.3
  progress_indicators: ^0.1.5
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  cloud_functions: ^0.3.0
  google_maps_flutter: ^0.5.27
  provider: ^4.0.5+1
  location: ^3.0.0
  geoflutterfire: ^2.1.0
  firebase_storage: ^3.1.5
  image_picker: ^0.6.6+1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_native_splash: ^0.1.9

  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: myfonts/MyFlutterApp.ttf

  uses-material-design: true
  assets:
    - images/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
